apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T11:13:05Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4695"
  uid: da249008-cec8-4f5c-8d5e-03e5698f454a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.169.204
  clusterIPs:
  - 10.107.169.204
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32363
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
